version: '3.8'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    networks:
      - my-app-network
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: appdb
    networks:
      - my-app-network
    volumes:
      - postgres_data:/var/lib/postgres/data

networks:
  my-app-network:
    driver: bridge

volumes:
  postgres_data: