version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"  # Optional: add if you need external access

volumes:
  mysql_data:
    name: mysql_data  # Optional: explicitly name the volume