version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.multistage
    ports:
      - "80:80"
    environment:
      NODE_ENV: production

  nginx:
    image: nginx:alpine
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web