version: '3.8'
services:
  frontend:
    image: nginx:alpine
    ports:
      - "443:443"
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: any
    secrets:
      - ssl_cert

  api:
    image: myapp/api:latest
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    environment:
      - REDIS_URL=redis://cache
      - DB_HOST=db

  cache:
    image: redis:alpine
    deploy:
      replicas: 2
      placement:
        constraints: [node.role == worker]

  db:
    image: postgres:13
    deploy:
      placement:
        constraints: [node.labels.db == true]
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"

volumes:
  db_data:

secrets:
  ssl_cert:
    external: true
  db_password:
    external: true