version: '3.8'
services:
  web:
    build: .
    ports:
      - "5001:5001"  # Changed to 5001 to avoid conflicts
    depends_on:
      - db
  
  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"